import type { AchievementDimension } from "../types/bullet-plan";
import type { RequirementCategory } from "../types/requirement";

export interface PhrasePattern {
  label: string;
  pattern: RegExp;
}

/**
 * Ordered longest and most resume-relevant first. Matches are returned with the
 * original JD casing so direct-keyword evidence remains verbatim.
 */
export const DIRECT_JD_PHRASE_PATTERNS: readonly PhrasePattern[] = [
  { label: "retrieval-augmented generation", pattern: /\bretrieval[- ]augmented generation\b/gi },
  { label: "large language models", pattern: /\blarge language models?\b/gi },
  { label: "cross-functional collaboration", pattern: /\bcross[- ]functional collaboration\b/gi },
  { label: "cross-functional teams", pattern: /\bcross[- ]functional teams?\b/gi },
  { label: "machine learning models", pattern: /\bmachine learning models?\b/gi },
  { label: "machine learning systems", pattern: /\bmachine learning systems?\b/gi },
  { label: "production ML systems", pattern: /\bproduction (?:ml|machine learning) systems?\b/gi },
  { label: "production environments", pattern: /\bproduction environments?\b/gi },
  { label: "deploy machine learning models", pattern: /\bdeploy(?:ed|ing|s)? machine learning models?\b/gi },
  { label: "model deployment", pattern: /\bmodel deployment\b/gi },
  { label: "model monitoring", pattern: /\bmodel monitoring\b/gi },
  { label: "monitor model performance", pattern: /\bmonitor(?:ed|ing|s)? model performance\b/gi },
  { label: "model performance", pattern: /\bmodel performance\b/gi },
  { label: "model serving", pattern: /\bmodel serving\b/gi },
  { label: "model lifecycle", pattern: /\bmodel lifecycle\b/gi },
  { label: "data pipelines", pattern: /\bdata pipelines?\b/gi },
  { label: "data quality", pattern: /\bdata quality\b/gi },
  { label: "data architecture", pattern: /\bdata architecture\b/gi },
  { label: "data warehouse", pattern: /\bdata warehouses?\b/gi },
  { label: "cloud infrastructure", pattern: /\bcloud infrastructure\b/gi },
  { label: "distributed systems", pattern: /\bdistributed systems?\b/gi },
  { label: "system architecture", pattern: /\bsystem architecture\b/gi },
  { label: "system design", pattern: /\bsystem design\b/gi },
  { label: "scalable architecture", pattern: /\bscalable (?:(?:machine learning|system|data|ml|cloud) )?architecture\b/gi },
  { label: "scalable systems", pattern: /\bscalable (?:software |data |ml |ai )?systems?\b/gi },
  { label: "scalable APIs", pattern: /\bscalable (?:(?:rest|http|web) )?apis?\b/gi },
  { label: "REST APIs", pattern: /\brest apis?\b/gi },
  { label: "ETL workflows", pattern: /\betl workflows?\b/gi },
  { label: "security testing", pattern: /\bsecurity testing\b/gi },
  { label: "application security controls", pattern: /\bapplication security controls?\b/gi },
  { label: "threat modeling", pattern: /\bthreat modeling\b/gi },
  { label: "vulnerability remediation", pattern: /\bvulnerability remediation\b/gi },
  { label: "automated testing", pattern: /\bautomated testing\b/gi },
  { label: "service reliability", pattern: /\bservice reliability\b/gi },
  { label: "delivery reliability", pattern: /\bdelivery reliability\b/gi },
  { label: "mentor engineers", pattern: /\bmentor(?:ed|ing|s)? engineers?\b/gi },
  { label: "CI/CD pipelines", pattern: /\bci\s*\/\s*cd pipelines?\b/gi },
  { label: "continuous integration", pattern: /\bcontinuous integration\b/gi },
  { label: "continuous delivery", pattern: /\bcontinuous (?:delivery|deployment)\b/gi },
  { label: "inference latency", pattern: /\binference latency\b/gi },
  { label: "response time", pattern: /\bresponse times?\b/gi },
  { label: "throughput", pattern: /\bthroughput\b/gi },
  { label: "performance optimization", pattern: /\bperformance optimization\b/gi },
  { label: "production reliability", pattern: /\bproduction reliability\b/gi },
  { label: "system reliability", pattern: /\bsystem reliability\b/gi },
  { label: "service availability", pattern: /\bservice availability\b/gi },
  { label: "observability", pattern: /\bobservability\b/gi },
  { label: "technical leadership", pattern: /\btechnical leadership\b/gi },
  { label: "technical strategy", pattern: /\btechnical strategy\b/gi },
  { label: "architecture decisions", pattern: /\barchitecture decisions?\b/gi },
  { label: "stakeholder communication", pattern: /\bstakeholder communication\b/gi },
  { label: "business requirements", pattern: /\bbusiness requirements?\b/gi },
  { label: "product and platform stakeholders", pattern: /\bproduct and platform stakeholders?\b/gi },
  { label: "product stakeholders", pattern: /\bproduct stakeholders?\b/gi },
  { label: "engineering stakeholders", pattern: /\bengineering stakeholders?\b/gi },
  { label: "customer experience", pattern: /\bcustomer experience\b/gi },
  { label: "cost efficiency", pattern: /\bcost efficiency\b/gi },
  { label: "operational efficiency", pattern: /\boperational efficiency\b/gi },
  { label: "time to market", pattern: /\btime to market\b/gi },
  { label: "security controls", pattern: /\bsecurity controls?\b/gi },
  { label: "security governance", pattern: /\bsecurity governance\b/gi },
  { label: "compliance readiness", pattern: /\bcompliance readiness\b/gi },
  { label: "regulatory compliance", pattern: /\bregulatory compliance\b/gi },
  { label: "automated testing", pattern: /\bautomated testing\b/gi },
  { label: "workflow automation", pattern: /\bworkflow automation\b/gi },
  { label: "technical documentation", pattern: /\btechnical documentation\b/gi },
  { label: "knowledge sharing", pattern: /\bknowledge sharing\b/gi },
];

export const EXPLICIT_TOOL_PATTERNS: readonly PhrasePattern[] = [
  { label: "GitHub Actions", pattern: /\bGitHub Actions\b/gi },
  { label: "scikit-learn", pattern: /\bscikit-learn\b/gi },
  { label: "Hugging Face", pattern: /\bHugging Face\b/gi },
  { label: "Node.js", pattern: /\bNode\.js\b/gi },
  { label: "FastAPI", pattern: /\bFastAPI\b/gi },
  { label: "Kubernetes", pattern: /\bKubernetes\b/gi },
  { label: "Docker", pattern: /\bDocker\b/gi },
  { label: "MLflow", pattern: /\bMLflow\b/gi },
  { label: "Prometheus", pattern: /\bPrometheus\b/gi },
  { label: "Grafana", pattern: /\bGrafana\b/gi },
  { label: "Airflow", pattern: /\bAirflow\b/gi },
  { label: "Apache Spark", pattern: /\b(?:Apache )?Spark\b/gi },
  { label: "Kafka", pattern: /\bKafka\b/gi },
  { label: "Databricks", pattern: /\bDatabricks\b/gi },
  { label: "Snowflake", pattern: /\bSnowflake\b/gi },
  { label: "Fivetran", pattern: /\bFivetran\b/gi },
  { label: "Terraform", pattern: /\bTerraform\b/gi },
  { label: "Jenkins", pattern: /\bJenkins\b/gi },
  { label: "PyTorch", pattern: /\bPyTorch\b/gi },
  { label: "TensorFlow", pattern: /\bTensorFlow\b/gi },
  { label: "LangChain", pattern: /\bLangChain\b/gi },
  { label: "LlamaIndex", pattern: /\bLlamaIndex\b/gi },
  { label: "PostgreSQL", pattern: /\bPostgreSQL\b/gi },
  { label: "MongoDB", pattern: /\bMongoDB\b/gi },
  { label: "Redis", pattern: /\bRedis\b/gi },
  { label: "AWS", pattern: /\bAWS\b/gi },
  { label: "Azure", pattern: /\bAzure\b/gi },
  { label: "GCP", pattern: /\bGCP\b/gi },
  { label: "Python", pattern: /\bPython\b/gi },
  { label: "TypeScript", pattern: /\bTypeScript\b/gi },
  { label: "JavaScript", pattern: /\bJavaScript\b/gi },
  { label: "Java", pattern: /\bJava\b/gi },
  { label: "Golang", pattern: /\b(?:Golang|Go)\b/gi },
  { label: "SQL", pattern: /\bSQL\b/gi },
  { label: "dbt", pattern: /\bdbt\b/gi },
  { label: "React", pattern: /\bReact\b/gi },
  { label: "Flask", pattern: /\bFlask\b/gi },
  { label: "Django", pattern: /\bDjango\b/gi },
];

export const SUPPORTING_BY_CATEGORY: Readonly<Record<RequirementCategory, readonly string[]>> = {
  "technical-responsibility": [
    "solution design",
    "design reviews",
    "automated testing",
    "delivery planning",
    "technical documentation",
  ],
  "technical-skill": [
    "code reviews",
    "unit testing",
    "integration testing",
    "performance profiling",
    "engineering standards",
  ],
  "tool-or-platform": [
    "platform integration",
    "configuration management",
    "release automation",
    "operational runbooks",
    "infrastructure as code",
  ],
  architecture: [
    "distributed systems",
    "service decomposition",
    "architecture decision records",
    "design reviews",
    "capacity planning",
    "fault-tolerant design",
  ],
  deployment: [
    "containerization",
    "CI/CD",
    "release automation",
    "blue-green deployment",
    "rollback automation",
    "model serving",
  ],
  monitoring: [
    "observability",
    "telemetry",
    "alerting",
    "performance dashboards",
    "drift detection",
    "incident response",
  ],
  performance: [
    "performance profiling",
    "caching",
    "dynamic batching",
    "load testing",
    "query optimization",
    "resource tuning",
  ],
  data: [
    "ETL",
    "data validation",
    "schema evolution",
    "workflow orchestration",
    "data lineage",
    "stream processing",
  ],
  security: [
    "threat modeling",
    "access controls",
    "secrets management",
    "security testing",
    "audit logging",
    "policy as code",
    "secure design reviews",
    "vulnerability scanning",
    "risk assessment",
    "least-privilege access",
    "compliance controls",
    "penetration testing",
    "security baselines",
    "remediation workflows",
  ],
  communication: [
    "requirements gathering",
    "technical presentations",
    "decision documentation",
    "stakeholder updates",
    "risk communication",
    "executive briefings",
  ],
  collaboration: [
    "cross-functional planning",
    "architecture workshops",
    "Agile delivery",
    "product partnership",
    "technical discovery",
    "dependency coordination",
  ],
  leadership: [
    "technical strategy",
    "architecture governance",
    "roadmap planning",
    "mentoring",
    "design reviews",
    "engineering standards",
  ],
  "business-outcome": [
    "product analytics",
    "service-level objectives",
    "customer feedback loops",
    "operational metrics",
    "value-stream mapping",
    "adoption analysis",
  ],
  education: ["knowledge sharing"],
  experience: ["technical ownership"],
  other: [
    "root-cause analysis",
    "continuous improvement",
    "technical documentation",
    "delivery planning",
  ],
};

export const SUPPORTING_BY_DIMENSION: Readonly<Record<AchievementDimension, readonly string[]>> = {
  "architecture-design": [
    "system design",
    "architecture decision records",
    "capacity planning",
    "design reviews",
    "service boundary definition",
    "reference architecture modeling",
    "scalability blueprints",
    "component decomposition",
  ],
  "production-delivery": [
    "release automation",
    "CI/CD",
    "deployment orchestration",
    "rollback strategy",
    "release gating",
    "environment promotion",
    "canary releases",
    "delivery runbooks",
  ],
  "performance-optimization": [
    "performance profiling",
    "load testing",
    "caching",
    "resource tuning",
    "dynamic batching",
    "hot-path optimization",
    "concurrency tuning",
    "latency budgeting",
  ],
  "reliability-observability": [
    "observability",
    "alerting",
    "incident response",
    "service-level objectives",
    "telemetry instrumentation",
    "error-budget tracking",
    "on-call playbooks",
    "health-check automation",
  ],
  "quality-automation": [
    "automated testing",
    "quality gates",
    "workflow orchestration",
    "continuous integration",
    "regression suites",
    "test data management",
    "contract testing",
    "release verification",
  ],
  "scalability-capacity": [
    "autoscaling",
    "capacity planning",
    "load balancing",
    "distributed processing",
    "partitioning strategies",
    "queue-backed fan-out",
    "elastic resource pools",
    "throughput planning",
  ],
  "cost-efficiency": [
    "resource right-sizing",
    "cost monitoring",
    "workload scheduling",
    "storage optimization",
    "idle-capacity reduction",
    "reserved-capacity planning",
    "spend anomaly detection",
    "unit-cost tracking",
  ],
  "security-governance": [
    "threat modeling",
    "access controls",
    "audit logging",
    "policy enforcement",
    "secrets management",
    "secure delivery checks",
    "compliance evidence collection",
    "privilege reviews",
  ],
  "data-quality": [
    "data validation",
    "schema checks",
    "data lineage",
    "quality monitoring",
    "anomaly detection",
    "reconciliation jobs",
    "contract tests for datasets",
    "freshness monitoring",
  ],
  "customer-business-impact": [
    "product analytics",
    "customer feedback loops",
    "operational metrics",
    "adoption analysis",
    "outcome instrumentation",
    "value hypothesis testing",
    "customer journey metrics",
    "impact scorecards",
  ],
  "cross-functional-alignment": [
    "requirements gathering",
    "architecture workshops",
    "stakeholder updates",
    "dependency coordination",
    "decision logs",
    "priority negotiation",
    "shared roadmap reviews",
    "interface agreements",
  ],
  "technical-leadership": [
    "technical strategy",
    "roadmap planning",
    "architecture governance",
    "engineering standards",
    "design authority reviews",
    "execution planning",
    "technical risk management",
    "ownership models",
  ],
  "mentoring-knowledge-sharing": [
    "mentoring",
    "pair programming",
    "technical workshops",
    "knowledge-base development",
    "onboarding guides",
    "code walkthroughs",
    "skills coaching",
    "practice playbooks",
  ],
  "implementation-integration": [
    "API integration",
    "integration testing",
    "interface contracts",
    "release planning",
    "handoff automation",
    "adapter development",
    "end-to-end wiring",
    "compatibility checks",
  ],
};

/**
 * Extra methods used only after category/dimension inventories are exhausted
 * under document-wide uniqueness locks.
 */
export const SUPPORTING_FALLBACK_POOL: readonly string[] = [
  "progressive delivery",
  "feature flagging",
  "chaos testing",
  "synthetic monitoring",
  "trace sampling",
  "log correlation",
  "metric cardinality control",
  "backpressure controls",
  "retry budgeting",
  "timeout tuning",
  "circuit breaking",
  "bulkhead isolation",
  "idempotent processing",
  "exactly-once safeguards",
  "schema registries",
  "event sourcing patterns",
  "change-data capture",
  "materialized views",
  "query federation",
  "index strategy reviews",
  "connection pooling",
  "memory profiling",
  "CPU affinity tuning",
  "GPU utilization tracking",
  "artifact signing",
  "supply-chain scanning",
  "configuration drift detection",
  "infrastructure as code reviews",
  "multi-region failover",
  "disaster-recovery drills",
  "backup validation",
  "cold-start reduction",
  "build cache optimization",
  "dependency upgrades",
  "API versioning",
  "backward-compatibility testing",
  "shadow traffic analysis",
  "experimentation frameworks",
  "guardrail policies",
  "runbook automation",
  "post-incident reviews",
  "error taxonomy design",
  "SLA negotiation support",
  "capacity forecasts",
  "traffic shaping",
  "priority queues",
  "work-stealing schedulers",
  "batch window tuning",
  "compaction strategies",
  "retention policy design",
];

export const OUTCOMES_BY_DIMENSION: Readonly<Record<AchievementDimension, readonly string[]>> = {
  "architecture-design": [
    "architectural scalability",
    "system maintainability",
    "design consistency",
    "platform extensibility",
  ],
  "production-delivery": [
    "deployment speed",
    "release reliability",
    "delivery frequency",
    "time to production",
  ],
  "performance-optimization": [
    "inference latency",
    "request throughput",
    "runtime efficiency",
    "processing time",
  ],
  "reliability-observability": [
    "service availability",
    "incident detection time",
    "production reliability",
    "mean time to recovery",
  ],
  "quality-automation": [
    "defect rate",
    "test coverage",
    "release quality",
    "manual effort",
  ],
  "scalability-capacity": [
    "traffic capacity",
    "processing scale",
    "concurrent workload support",
    "peak-load resilience",
  ],
  "cost-efficiency": [
    "cloud cost efficiency",
    "infrastructure utilization",
    "operating cost",
    "resource efficiency",
  ],
  "security-governance": [
    "security posture",
    "compliance readiness",
    "vulnerability exposure",
    "auditability",
  ],
  "data-quality": [
    "data accuracy",
    "pipeline reliability",
    "data freshness",
    "quality incident rate",
  ],
  "customer-business-impact": [
    "customer satisfaction",
    "feature adoption",
    "business efficiency",
    "time to value",
  ],
  "cross-functional-alignment": [
    "stakeholder alignment",
    "delivery predictability",
    "decision turnaround time",
    "cross-team execution",
  ],
  "technical-leadership": [
    "engineering velocity",
    "architecture consistency",
    "technical decision quality",
    "roadmap execution",
  ],
  "mentoring-knowledge-sharing": [
    "team productivity",
    "onboarding time",
    "engineering capability",
    "knowledge retention",
  ],
  "implementation-integration": [
    "integration reliability",
    "feature delivery speed",
    "system interoperability",
    "implementation efficiency",
  ],
};

export const ACTION_VERBS_BY_DIMENSION: Readonly<Record<AchievementDimension, readonly string[]>> = {
  "architecture-design": ["Architected", "Designed", "Engineered", "Established"],
  "production-delivery": ["Deployed", "Productionized", "Launched", "Delivered"],
  "performance-optimization": ["Optimized", "Accelerated", "Tuned", "Streamlined"],
  "reliability-observability": ["Stabilized", "Instrumented", "Strengthened", "Hardened"],
  "quality-automation": ["Automated", "Standardized", "Orchestrated", "Validated"],
  "scalability-capacity": ["Scaled", "Expanded", "Modernized", "Reengineered"],
  "cost-efficiency": ["Consolidated", "Right-sized", "Rationalized", "Optimized"],
  "security-governance": ["Secured", "Governed", "Remediated", "Hardened"],
  "data-quality": ["Engineered", "Validated", "Orchestrated", "Standardized"],
  "customer-business-impact": ["Transformed", "Enabled", "Improved", "Delivered"],
  "cross-functional-alignment": ["Led", "Coordinated", "Facilitated", "Aligned"],
  "technical-leadership": ["Spearheaded", "Directed", "Championed", "Guided"],
  "mentoring-knowledge-sharing": ["Mentored", "Coached", "Guided", "Established"],
  "implementation-integration": ["Implemented", "Integrated", "Developed", "Built"],
};

export const CATEGORY_OUTCOME_HINTS: Readonly<Record<RequirementCategory, readonly string[]>> = {
  "technical-responsibility": ["delivery effectiveness", "engineering productivity"],
  "technical-skill": ["implementation quality", "engineering efficiency"],
  "tool-or-platform": ["platform reliability", "developer productivity"],
  architecture: ["architectural scalability", "system maintainability"],
  deployment: ["deployment speed", "release reliability"],
  monitoring: ["incident detection time", "production reliability"],
  performance: ["runtime efficiency", "processing latency"],
  data: ["pipeline reliability", "data quality"],
  security: ["security posture", "compliance readiness"],
  communication: ["stakeholder alignment", "decision turnaround time"],
  collaboration: ["cross-team execution", "delivery predictability"],
  leadership: ["engineering velocity", "roadmap execution"],
  "business-outcome": ["business efficiency", "customer value"],
  education: ["knowledge transfer"],
  experience: ["delivery ownership"],
  other: ["operational effectiveness", "delivery quality"],
};


export const ACTION_VERBS_BY_CATEGORY: Readonly<Record<RequirementCategory, readonly string[]>> = {
  "technical-responsibility": ["Implemented", "Developed", "Built", "Engineered"],
  "technical-skill": ["Applied", "Leveraged", "Implemented", "Integrated"],
  "tool-or-platform": ["Integrated", "Implemented", "Deployed", "Configured"],
  architecture: ["Architected", "Designed", "Engineered", "Established"],
  deployment: ["Deployed", "Productionized", "Launched", "Automated"],
  monitoring: ["Instrumented", "Monitored", "Stabilized", "Strengthened"],
  performance: ["Optimized", "Accelerated", "Tuned", "Streamlined"],
  data: ["Engineered", "Orchestrated", "Built", "Automated"],
  security: ["Secured", "Hardened", "Remediated", "Governed", "Assessed"],
  communication: ["Communicated", "Presented", "Translated", "Facilitated"],
  collaboration: ["Led", "Coordinated", "Facilitated", "Aligned"],
  leadership: ["Spearheaded", "Directed", "Mentored", "Guided"],
  "business-outcome": ["Improved", "Transformed", "Enabled", "Delivered"],
  education: ["Completed"],
  experience: ["Delivered"],
  other: ["Improved", "Resolved", "Implemented", "Delivered"],
};
