export const SKILL_CATEGORY_ORDER = [
  "Programming Languages",
  "AI & Machine Learning",
  "Generative AI",
  "Data Engineering",
  "MLOps & Model Operations",
  "Cloud & Infrastructure",
  "Frameworks & APIs",
  "Databases & Storage",
  "DevOps & CI/CD",
  "Monitoring & Observability",
  "Security & Compliance",
  "Architecture & Engineering",
  "Leadership & Delivery",
  // Additive multi-stack categories (original categories above are unchanged).
  "Mobile Development",
  "QA & Test Automation",
  "Embedded Systems",
  "Blockchain",
] as const;

export type SkillCategoryName = (typeof SKILL_CATEGORY_ORDER)[number];

export interface SkillDefinition {
  key: string;
  name: string;
  category: SkillCategoryName;
  aliases: string[];
  caseSensitive?: boolean;
}

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  { key: "PYTHON", name: "Python", category: "Programming Languages", aliases: ["Python"] },
  { key: "JAVA", name: "Java", category: "Programming Languages", aliases: ["Java"] },
  { key: "JAVASCRIPT", name: "JavaScript", category: "Programming Languages", aliases: ["JavaScript", "Javascript"] },
  { key: "C", name: "C", category: "Programming Languages", aliases: ["C"], caseSensitive: true },
  { key: "CPP", name: "C++", category: "Programming Languages", aliases: ["C++", "Cpp"] },
  { key: "RUST", name: "Rust", category: "Programming Languages", aliases: ["Rust"] },
  { key: "SWIFT", name: "Swift", category: "Programming Languages", aliases: ["Swift"] },
  { key: "KOTLIN", name: "Kotlin", category: "Programming Languages", aliases: ["Kotlin"] },
  { key: "SOLIDITY", name: "Solidity", category: "Programming Languages", aliases: ["Solidity"] },
  { key: "TYPESCRIPT", name: "TypeScript", category: "Programming Languages", aliases: ["TypeScript", "Typescript"] },
  { key: "GO", name: "Go", category: "Programming Languages", aliases: ["Go", "Golang"], caseSensitive: true },
  { key: "CPP", name: "C++", category: "Programming Languages", aliases: ["C++"] },
  { key: "CSHARP", name: "C#", category: "Programming Languages", aliases: ["C#", ".NET", "dotnet"] },
  { key: "SQL", name: "SQL", category: "Programming Languages", aliases: ["SQL"], caseSensitive: true },
  { key: "R_LANG", name: "R", category: "Programming Languages", aliases: ["R"], caseSensitive: true },
  { key: "SCALA", name: "Scala", category: "Programming Languages", aliases: ["Scala"] },
  { key: "RUST", name: "Rust", category: "Programming Languages", aliases: ["Rust"] },
  { key: "BASH", name: "Bash", category: "Programming Languages", aliases: ["Bash", "shell scripting"] },
  { key: "HTML", name: "HTML", category: "Programming Languages", aliases: ["HTML"], caseSensitive: true },
  { key: "CSS", name: "CSS", category: "Programming Languages", aliases: ["CSS"], caseSensitive: true },

  { key: "MACHINE_LEARNING", name: "Machine Learning", category: "AI & Machine Learning", aliases: ["machine learning", "ML models", "ML model"] },
  { key: "DEEP_LEARNING", name: "Deep Learning", category: "AI & Machine Learning", aliases: ["deep learning", "neural networks", "neural network"] },
  { key: "NLP", name: "Natural Language Processing", category: "AI & Machine Learning", aliases: ["natural language processing", "NLP"] },
  { key: "COMPUTER_VISION", name: "Computer Vision", category: "AI & Machine Learning", aliases: ["computer vision"] },
  { key: "MODEL_EVALUATION", name: "Model Evaluation", category: "AI & Machine Learning", aliases: ["model evaluation", "evaluate models", "evaluation metrics"] },
  { key: "FINE_TUNING", name: "Model Fine-Tuning", category: "AI & Machine Learning", aliases: ["fine-tuning", "fine tuning", "fine-tune"] },
  { key: "AB_TESTING", name: "A/B Testing", category: "AI & Machine Learning", aliases: ["A/B testing", "A-B testing", "experimentation"] },
  { key: "STATISTICS", name: "Statistics", category: "AI & Machine Learning", aliases: ["statistics", "statistical analysis"] },
  { key: "EXPERIMENT_DESIGN", name: "Experiment Design", category: "AI & Machine Learning", aliases: ["experiment design", "experimental design"] },
  { key: "RECOMMENDER", name: "Recommendation Systems", category: "AI & Machine Learning", aliases: ["recommendation systems", "recommender systems", "recommendation engine"] },
  { key: "TIME_SERIES", name: "Time-Series Modeling", category: "AI & Machine Learning", aliases: ["time series", "forecasting"] },

  { key: "GENERATIVE_AI", name: "Generative AI", category: "Generative AI", aliases: ["generative AI", "GenAI", "Gen AI"] },
  { key: "LLMS", name: "Large Language Models", category: "Generative AI", aliases: ["large language models", "LLMs", "LLM"] },
  { key: "RAG", name: "Retrieval-Augmented Generation", category: "Generative AI", aliases: ["retrieval-augmented generation", "retrieval augmented generation", "RAG"] },
  { key: "EMBEDDINGS", name: "Embeddings", category: "Generative AI", aliases: ["embeddings", "vector embeddings"] },
  { key: "PROMPT_ENGINEERING", name: "Prompt Engineering", category: "Generative AI", aliases: ["prompt engineering", "prompt design"] },
  { key: "AGENTIC_AI", name: "Agentic AI", category: "Generative AI", aliases: ["agentic AI", "AI agents", "agent workflows"] },
  { key: "MULTI_AGENT", name: "Multi-Agent Systems", category: "Generative AI", aliases: ["multi-agent", "multi agent", "multi-agent systems"] },
  { key: "RETRIEVAL_EVALUATION", name: "Retrieval Evaluation", category: "Generative AI", aliases: ["retrieval evaluation", "retrieval quality"] },
  { key: "LLM_EVALUATION", name: "LLM Evaluation", category: "Generative AI", aliases: ["LLM evaluation", "evaluate LLMs", "LLM quality"] },
  { key: "LLM_ORCHESTRATION", name: "LLM Orchestration", category: "Generative AI", aliases: ["LLM orchestration"] },

  { key: "DATA_ENGINEERING", name: "Data Engineering", category: "Data Engineering", aliases: ["data engineering"] },
  { key: "DATA_PIPELINES", name: "Data Pipelines", category: "Data Engineering", aliases: ["data pipelines", "data pipeline"] },
  { key: "ETL_ELT", name: "ETL/ELT", category: "Data Engineering", aliases: ["ETL", "ELT", "ETL/ELT"] },
  { key: "DATA_MODELING", name: "Data Modeling", category: "Data Engineering", aliases: ["data modeling", "data modelling"] },
  { key: "STREAMING_DATA", name: "Streaming Data", category: "Data Engineering", aliases: ["streaming data", "stream processing", "streaming pipelines"] },
  { key: "BATCH_PROCESSING", name: "Batch Processing", category: "Data Engineering", aliases: ["batch processing", "batch pipelines"] },
  { key: "DATA_QUALITY", name: "Data Quality", category: "Data Engineering", aliases: ["data quality", "data validation"] },
  { key: "DISTRIBUTED_DATA_PROCESSING", name: "Distributed Data Processing", category: "Data Engineering", aliases: ["distributed data processing"] },
  { key: "SPARK", name: "Apache Spark", category: "Data Engineering", aliases: ["Apache Spark", "Spark", "PySpark"] },
  { key: "AIRFLOW", name: "Apache Airflow", category: "Data Engineering", aliases: ["Apache Airflow", "Airflow"] },
  { key: "KAFKA", name: "Apache Kafka", category: "Data Engineering", aliases: ["Apache Kafka", "Kafka"] },
  { key: "DATABRICKS", name: "Databricks", category: "Data Engineering", aliases: ["Databricks"] },
  { key: "SNOWFLAKE", name: "Snowflake", category: "Data Engineering", aliases: ["Snowflake"] },
  { key: "DBT", name: "dbt", category: "Data Engineering", aliases: ["dbt"], caseSensitive: true },
  { key: "FIVETRAN", name: "Fivetran", category: "Data Engineering", aliases: ["Fivetran"] },

  { key: "MLOPS", name: "MLOps", category: "MLOps & Model Operations", aliases: ["MLOps", "ML Ops"] },
  { key: "MLFLOW", name: "MLflow", category: "MLOps & Model Operations", aliases: ["MLflow"] },
  { key: "MODEL_DEPLOYMENT", name: "Model Deployment", category: "MLOps & Model Operations", aliases: ["model deployment", "deploy models", "deploy machine learning models", "productionize models"] },
  { key: "MODEL_MONITORING", name: "Model Monitoring", category: "MLOps & Model Operations", aliases: ["model monitoring", "monitor models", "monitoring model performance"] },
  { key: "MODEL_SERVING", name: "Model Serving", category: "MLOps & Model Operations", aliases: ["model serving", "inference serving", "serving models"] },
  { key: "DRIFT_DETECTION", name: "Drift Detection", category: "MLOps & Model Operations", aliases: ["drift detection", "data drift", "model drift"] },
  { key: "EXPERIMENT_TRACKING", name: "Experiment Tracking", category: "MLOps & Model Operations", aliases: ["experiment tracking"] },
  { key: "FEATURE_STORES", name: "Feature Stores", category: "MLOps & Model Operations", aliases: ["feature store", "feature stores"] },

  { key: "AWS", name: "AWS", category: "Cloud & Infrastructure", aliases: ["AWS", "Amazon Web Services"], caseSensitive: true },
  { key: "AZURE", name: "Microsoft Azure", category: "Cloud & Infrastructure", aliases: ["Microsoft Azure", "Azure"] },
  { key: "GCP", name: "Google Cloud Platform", category: "Cloud & Infrastructure", aliases: ["Google Cloud Platform", "GCP", "Google Cloud"] },
  { key: "CLOUD_COMPUTING", name: "Cloud Computing", category: "Cloud & Infrastructure", aliases: ["cloud computing", "cloud platforms", "cloud infrastructure"] },
  { key: "DOCKER", name: "Docker", category: "Cloud & Infrastructure", aliases: ["Docker"] },
  { key: "KUBERNETES", name: "Kubernetes", category: "Cloud & Infrastructure", aliases: ["Kubernetes", "K8s"] },
  { key: "CONTAINERIZATION", name: "Containerization", category: "Cloud & Infrastructure", aliases: ["containerization", "containerized"] },
  { key: "CONTAINER_ORCHESTRATION", name: "Container Orchestration", category: "Cloud & Infrastructure", aliases: ["container orchestration"] },
  { key: "TERRAFORM", name: "Terraform", category: "Cloud & Infrastructure", aliases: ["Terraform"] },
  { key: "SERVERLESS", name: "Serverless Architecture", category: "Cloud & Infrastructure", aliases: ["serverless", "serverless architecture"] },

  { key: "PYTORCH", name: "PyTorch", category: "Frameworks & APIs", aliases: ["PyTorch"] },
  { key: "TENSORFLOW", name: "TensorFlow", category: "Frameworks & APIs", aliases: ["TensorFlow"] },
  { key: "SCIKIT_LEARN", name: "scikit-learn", category: "Frameworks & APIs", aliases: ["scikit-learn", "sklearn"] },
  { key: "XGBOOST", name: "XGBoost", category: "Frameworks & APIs", aliases: ["XGBoost"] },
  { key: "HUGGING_FACE", name: "Hugging Face", category: "Frameworks & APIs", aliases: ["Hugging Face", "Transformers"] },
  { key: "LANGCHAIN", name: "LangChain", category: "Frameworks & APIs", aliases: ["LangChain"] },
  { key: "LLAMAINDEX", name: "LlamaIndex", category: "Frameworks & APIs", aliases: ["LlamaIndex"] },
  { key: "OPENAI_API", name: "OpenAI API", category: "Frameworks & APIs", aliases: ["OpenAI API", "OpenAI"] },
  { key: "ANTHROPIC_API", name: "Anthropic API", category: "Frameworks & APIs", aliases: ["Anthropic API", "Claude API"] },
  { key: "FASTAPI", name: "FastAPI", category: "Frameworks & APIs", aliases: ["FastAPI"] },
  { key: "FLASK", name: "Flask", category: "Frameworks & APIs", aliases: ["Flask"] },
  { key: "DJANGO", name: "Django", category: "Frameworks & APIs", aliases: ["Django"] },
  { key: "SPRING_BOOT", name: "Spring Boot", category: "Frameworks & APIs", aliases: ["Spring Boot"] },
  { key: "NODE_JS", name: "Node.js", category: "Frameworks & APIs", aliases: ["Node.js", "NodeJS", "Node JS"] },
  { key: "REACT", name: "React.js", category: "Frameworks & APIs", aliases: ["React", "React.js"] },
  { key: "NEXT_JS", name: "Next.js", category: "Frameworks & APIs", aliases: ["Next.js", "NextJS"] },
  { key: "VUE", name: "Vue.js", category: "Frameworks & APIs", aliases: ["Vue.js", "Vue"] },
  { key: "ANGULAR", name: "Angular", category: "Frameworks & APIs", aliases: ["Angular"] },
  { key: "TAILWIND_CSS", name: "Tailwind CSS", category: "Frameworks & APIs", aliases: ["Tailwind CSS", "TailwindCSS", "Tailwind"] },
  { key: "CSS_MODULES", name: "CSS Modules", category: "Frameworks & APIs", aliases: ["CSS Modules", "CSS modules"] },
  { key: "DAISYUI", name: "DaisyUI", category: "Frameworks & APIs", aliases: ["DaisyUI", "Daisy UI", "component libraries such as DaisyUI"] },
  { key: "REST_APIS", name: "RESTful APIs", category: "Frameworks & APIs", aliases: ["REST API", "REST APIs", "RESTful APIs", "RESTful services", "RESTful API"] },
  { key: "WEBSOCKETS", name: "WebSockets", category: "Frameworks & APIs", aliases: ["WebSockets", "WebSocket", "WebSocket APIs", "native WebSocket APIs"] },
  { key: "GRPC", name: "gRPC", category: "Frameworks & APIs", aliases: ["gRPC"] },
  { key: "GRAPHQL", name: "GraphQL", category: "Frameworks & APIs", aliases: ["GraphQL"] },
  { key: "TDD", name: "Test-Driven Development", category: "Architecture & Engineering", aliases: ["Test-Driven Development", "TDD", "test-driven development"] },
  { key: "VITEST", name: "Vitest", category: "DevOps & CI/CD", aliases: ["Vitest"] },
  { key: "CYPRESS", name: "Cypress", category: "DevOps & CI/CD", aliases: ["Cypress"] },
  { key: "JIRA", name: "Jira", category: "Leadership & Delivery", aliases: ["Jira"] },
  { key: "CONFLUENCE", name: "Confluence", category: "Leadership & Delivery", aliases: ["Confluence"] },

  { key: "POSTGRESQL", name: "PostgreSQL", category: "Databases & Storage", aliases: ["PostgreSQL", "Postgres"] },
  { key: "MYSQL", name: "MySQL", category: "Databases & Storage", aliases: ["MySQL"] },
  { key: "MONGODB", name: "MongoDB", category: "Databases & Storage", aliases: ["MongoDB"] },
  { key: "REDIS", name: "Redis", category: "Databases & Storage", aliases: ["Redis"] },
  { key: "ELASTICSEARCH", name: "Elasticsearch", category: "Databases & Storage", aliases: ["Elasticsearch", "Elastic Search"] },
  { key: "DYNAMODB", name: "DynamoDB", category: "Databases & Storage", aliases: ["DynamoDB"] },
  { key: "BIGQUERY", name: "BigQuery", category: "Databases & Storage", aliases: ["BigQuery"] },
  { key: "REDSHIFT", name: "Amazon Redshift", category: "Databases & Storage", aliases: ["Amazon Redshift", "Redshift"] },
  { key: "VECTOR_DATABASES", name: "Vector Databases", category: "Databases & Storage", aliases: ["vector database", "vector databases", "vector store", "vector stores"] },

  { key: "CI_CD", name: "CI/CD", category: "DevOps & CI/CD", aliases: ["CI/CD", "continuous integration", "continuous delivery", "continuous deployment"] },
  { key: "GITHUB_ACTIONS", name: "GitHub Actions", category: "DevOps & CI/CD", aliases: ["GitHub Actions"] },
  { key: "GITLAB_CI", name: "GitLab CI", category: "DevOps & CI/CD", aliases: ["GitLab CI", "GitLab CI/CD"] },
  { key: "JENKINS", name: "Jenkins", category: "DevOps & CI/CD", aliases: ["Jenkins"] },
  { key: "GIT", name: "Git", category: "DevOps & CI/CD", aliases: ["Git"], caseSensitive: true },
  { key: "LINUX", name: "Linux", category: "DevOps & CI/CD", aliases: ["Linux"] },
  { key: "DEPLOYMENT_AUTOMATION", name: "Deployment Automation", category: "DevOps & CI/CD", aliases: ["deployment automation", "automated deployments"] },

  { key: "PROMETHEUS", name: "Prometheus", category: "Monitoring & Observability", aliases: ["Prometheus"] },
  { key: "GRAFANA", name: "Grafana", category: "Monitoring & Observability", aliases: ["Grafana"] },
  { key: "OPENTELEMETRY", name: "OpenTelemetry", category: "Monitoring & Observability", aliases: ["OpenTelemetry"] },
  { key: "OBSERVABILITY", name: "Observability", category: "Monitoring & Observability", aliases: ["observability"] },
  { key: "LOGGING", name: "Logging", category: "Monitoring & Observability", aliases: ["logging", "structured logging"] },
  { key: "MONITORING", name: "System Monitoring", category: "Monitoring & Observability", aliases: ["system monitoring", "application monitoring"] },

  { key: "SECURITY", name: "Application Security", category: "Security & Compliance", aliases: ["application security", "software security", "secure applications"] },
  { key: "IAM", name: "Identity and Access Management", category: "Security & Compliance", aliases: ["identity and access management", "IAM"] },
  { key: "OAUTH", name: "OAuth", category: "Security & Compliance", aliases: ["OAuth", "OAuth 2.0"] },
  { key: "OIDC", name: "OpenID Connect", category: "Security & Compliance", aliases: ["OpenID Connect", "OIDC"] },
  { key: "ENCRYPTION", name: "Encryption", category: "Security & Compliance", aliases: ["encryption", "encrypted"] },
  { key: "SOC2", name: "SOC 2", category: "Security & Compliance", aliases: ["SOC 2", "SOC2"] },
  { key: "HIPAA", name: "HIPAA", category: "Security & Compliance", aliases: ["HIPAA"] },
  { key: "GDPR", name: "GDPR", category: "Security & Compliance", aliases: ["GDPR"] },

  { key: "SYSTEM_DESIGN", name: "System Design", category: "Architecture & Engineering", aliases: ["system design", "systems design"] },
  { key: "DISTRIBUTED_SYSTEMS", name: "Distributed Systems", category: "Architecture & Engineering", aliases: ["distributed systems", "distributed system"] },
  { key: "MICROSERVICES", name: "Microservices", category: "Architecture & Engineering", aliases: ["microservices", "microservice architecture"] },
  { key: "EVENT_DRIVEN", name: "Event-Driven Architecture", category: "Architecture & Engineering", aliases: ["event-driven architecture", "event driven architecture"] },
  { key: "API_DESIGN", name: "API Design", category: "Architecture & Engineering", aliases: ["API design", "design APIs"] },
  { key: "SCALABILITY", name: "Scalable Systems", category: "Architecture & Engineering", aliases: ["scalable systems", "scalability", "high-scale"] },
  { key: "RELIABILITY", name: "System Reliability", category: "Architecture & Engineering", aliases: ["system reliability", "reliable systems", "reliability"] },
  { key: "HIGH_AVAILABILITY", name: "High Availability", category: "Architecture & Engineering", aliases: ["high availability", "highly available"] },
  { key: "PERFORMANCE_OPTIMIZATION", name: "Performance Optimization", category: "Architecture & Engineering", aliases: ["performance optimization", "optimize performance", "improve performance"] },

  { key: "AGILE", name: "Agile Delivery", category: "Leadership & Delivery", aliases: ["Agile", "Agile delivery"] },
  { key: "SCRUM", name: "Scrum", category: "Leadership & Delivery", aliases: ["Scrum"] },
  { key: "TECHNICAL_LEADERSHIP", name: "Technical Leadership", category: "Leadership & Delivery", aliases: ["technical leadership", "lead technical", "technical lead"] },
  { key: "MENTORING", name: "Mentoring", category: "Leadership & Delivery", aliases: ["mentor engineers", "mentoring", "mentor team members"] },
  { key: "STAKEHOLDER_MANAGEMENT", name: "Stakeholder Management", category: "Leadership & Delivery", aliases: ["stakeholder management", "manage stakeholders", "stakeholder communication"] },
  { key: "CROSS_FUNCTIONAL", name: "Cross-Functional Collaboration", category: "Leadership & Delivery", aliases: ["cross-functional collaboration", "cross functional collaboration", "collaborate with product", "partner with product"] },
  { key: "REQUIREMENTS_GATHERING", name: "Requirements Gathering", category: "Leadership & Delivery", aliases: ["requirements gathering", "gather requirements", "translate business requirements"] },
  { key: "TECHNICAL_DOCUMENTATION", name: "Technical Documentation", category: "Leadership & Delivery", aliases: ["technical documentation", "document technical decisions", "documentation"] },

  // Additive multi-stack skills (original definitions above are unchanged).
  { key: "PANDAS", name: "pandas", category: "Data Engineering", aliases: ["pandas", "Pandas"] },
  { key: "IOS", name: "iOS", category: "Mobile Development", aliases: ["iOS", "iOS development"] },
  { key: "ANDROID", name: "Android", category: "Mobile Development", aliases: ["Android", "Android development"] },
  { key: "REACT_NATIVE", name: "React Native", category: "Mobile Development", aliases: ["React Native"] },
  { key: "FLUTTER", name: "Flutter", category: "Mobile Development", aliases: ["Flutter"] },
  { key: "MOBILE_UI", name: "Mobile UI Development", category: "Mobile Development", aliases: ["mobile UI", "mobile user interfaces"] },
  { key: "PLAYWRIGHT", name: "Playwright", category: "QA & Test Automation", aliases: ["Playwright"] },
  { key: "SELENIUM", name: "Selenium", category: "QA & Test Automation", aliases: ["Selenium"] },
  { key: "JUNIT", name: "JUnit", category: "QA & Test Automation", aliases: ["JUnit"] },
  { key: "TESTNG", name: "TestNG", category: "QA & Test Automation", aliases: ["TestNG"] },
  { key: "TEST_AUTOMATION", name: "Test Automation", category: "QA & Test Automation", aliases: ["test automation", "automated testing frameworks"] },
  { key: "TEST_STRATEGY", name: "Test Strategy", category: "QA & Test Automation", aliases: ["test strategy", "testing strategy"] },
  { key: "RTOS", name: "RTOS", category: "Embedded Systems", aliases: ["RTOS", "real-time operating system"] },
  { key: "EMBEDDED_LINUX", name: "Embedded Linux", category: "Embedded Systems", aliases: ["Embedded Linux", "embedded Linux"] },
  { key: "FIRMWARE", name: "Firmware Development", category: "Embedded Systems", aliases: ["firmware", "firmware development"] },
  { key: "MICROCONTROLLERS", name: "Microcontrollers", category: "Embedded Systems", aliases: ["microcontrollers", "MCU"] },
  { key: "ETHEREUM", name: "Ethereum", category: "Blockchain", aliases: ["Ethereum"] },
  { key: "WEB3", name: "Web3", category: "Blockchain", aliases: ["Web3", "web3"] },
  { key: "HARDHAT", name: "Hardhat", category: "Blockchain", aliases: ["Hardhat"] },
  { key: "SMART_CONTRACTS", name: "Smart Contracts", category: "Blockchain", aliases: ["smart contracts", "smart contract development"] },
];

export interface SkillInferenceRule {
  triggerKeys: string[];
  inferredKey: string;
  rationale: string;
}

export const SKILL_INFERENCE_RULES: SkillInferenceRule[] = [
  { triggerKeys: ["KUBERNETES"], inferredKey: "CONTAINER_ORCHESTRATION", rationale: "Kubernetes directly implies container orchestration." },
  { triggerKeys: ["DOCKER"], inferredKey: "CONTAINERIZATION", rationale: "Docker directly implies containerization." },
  { triggerKeys: ["AWS", "AZURE", "GCP"], inferredKey: "CLOUD_COMPUTING", rationale: "A named public-cloud platform directly supports cloud-computing capability." },
  { triggerKeys: ["RAG"], inferredKey: "EMBEDDINGS", rationale: "RAG implementations require embedding-based retrieval." },
  { triggerKeys: ["RAG"], inferredKey: "VECTOR_DATABASES", rationale: "RAG commonly requires a vector retrieval store." },
  { triggerKeys: ["RAG"], inferredKey: "RETRIEVAL_EVALUATION", rationale: "Production RAG work strongly implies retrieval-quality evaluation." },
  { triggerKeys: ["LANGCHAIN", "LLAMAINDEX"], inferredKey: "LLM_ORCHESTRATION", rationale: "LLM frameworks directly support orchestration workflows." },
  { triggerKeys: ["MLFLOW"], inferredKey: "EXPERIMENT_TRACKING", rationale: "MLflow directly supports experiment tracking." },
  { triggerKeys: ["MODEL_DEPLOYMENT"], inferredKey: "MLOPS", rationale: "Production model deployment is a core MLOps capability." },
  { triggerKeys: ["MODEL_MONITORING"], inferredKey: "MLOPS", rationale: "Production model monitoring is a core MLOps capability." },
  { triggerKeys: ["DATA_PIPELINES"], inferredKey: "ETL_ELT", rationale: "Building data pipelines strongly implies ETL/ELT practices." },
  { triggerKeys: ["KAFKA"], inferredKey: "STREAMING_DATA", rationale: "Kafka directly supports streaming-data architectures." },
  { triggerKeys: ["SPARK"], inferredKey: "DISTRIBUTED_DATA_PROCESSING", rationale: "Spark directly supports distributed data processing." },
  { triggerKeys: ["REST_APIS", "GRPC", "GRAPHQL"], inferredKey: "API_DESIGN", rationale: "Building service interfaces strongly implies API design." },
  { triggerKeys: ["CI_CD"], inferredKey: "DEPLOYMENT_AUTOMATION", rationale: "CI/CD directly implies deployment automation." },
  { triggerKeys: ["PROMETHEUS", "GRAFANA", "OPENTELEMETRY"], inferredKey: "OBSERVABILITY", rationale: "Observability tools directly support production observability." },
  { triggerKeys: ["DISTRIBUTED_SYSTEMS"], inferredKey: "SCALABILITY", rationale: "Distributed-system design strongly implies scalability engineering." },
];

export const SKILL_DEFINITION_BY_KEY = new Map(
  SKILL_DEFINITIONS.map((definition) => [definition.key, definition] as const),
);
